name: prifidoiot
on:
  workflow_dispatch:
  push:
    branches: [master, "*rel"]
  pull_request:
    branches: [master, "*rel"]
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: scm checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: setup-java
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: "17"
          distribution: "temurin"
      - name: build
        run: |
          mvn clean install
          cd component-samples && tar -czvf demo.tar.gz demo && mv demo.tar.gz ..
      - name: checkout test-fidoiot
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: fido-device-onboard/test-fidoiot
          ref: master
          path: test-fidoiot
      - name: Add host to /etc/hosts
        run: |
          sudo echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts
      - name: run smoke test
        run: |
          mkdir -p test-fidoiot/binaries/pri-fidoiot
          cp -r component-samples/demo/* test-fidoiot/binaries/pri-fidoiot
          cp -r test-fidoiot/binaries/pri-fidoiot/device/* test-fidoiot/
          cd test-fidoiot/binaries/pri-fidoiot/scripts
          bash demo_ca.sh
          bash web_csr_req.sh
          bash user_csr_req.sh
          bash keys_gen.sh
          chmod -R 777 secrets/
          cp -r service.env secrets/ ../aio/
          cp -r secrets/ ../db/
          sed -i '/<security-constraint>/,/<.security-constraint>/d' ../aio/WEB-INF/web.xml
          sed -i '/^innodb/d' ../db/custom/config-file.cnf
          cd ${{ github.workspace }}/test-fidoiot
          export TEST_DIR=$PWD
          mvn clean test -Dgroups=fdo_pri_smoketest
      - name: archive artifacts
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: demo.tar.gz
          path: demo.tar.gz
          retention-days: 5
        if: github.event_name != 'pull_request'
